services:
    postgres-db:
        image: postgres:17
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
    flyway:
        image: flyway/flyway:11-alpine
        command: -url=jdbc:postgresql://postgres-db:5432/news_db -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
        volumes:
            - ./flyway-migrations:/flyway/sql
        depends_on:
            - postgres-db
